name: Website Monitor

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute (GitHub minimum is 5 minutes)
  workflow_dispatch:

jobs:
  monitor-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb libgtk-3-0 libxtst6 libx11-xcb1 libdbus-glib-1-2

      - name: Install Geckodriver
        run: |
          sudo apt-get install -y firefox-geckodriver
          geckodriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.18.1

      - name: Verify installations
        run: |
          firefox --version
          geckodriver --version
          python -c "import selenium; print(f'Selenium version: {selenium.__version__}')"

      - name: Run website monitor
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          sleep 3
          python website_monitor.py
